environment:
  version: 2.1.0
version: '{build}-{branch}'
image: Visual Studio 2017
configuration: Release
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: $(version)
  package_version: $(version)
  assembly_version: $(version)
  file_version: $(version)
  informational_version: $(version)
before_build:
- cmd: nuget restore ".\src\CCSWE.Core.sln"
build:
  publish_nuget: true
  publish_nuget_symbols: true
  include_nuget_references: true
  verbosity: minimal